### ISSUE TITLE
Unable to find data/v0.5

### ISSUE THREAD

**Issue by axh24** [saezlab/DepMap-BioCypher#2]
Hi,

Thank you for building the adapter to access DepMap. I am wondering where I can find the following input data:

DepMapNodeType.GENE.value: "data/v0.5/genes/gene_all.csv",
DepMapNodeType.COMPOUND.value: "data/v0.5/compounds/compounds_all.csv",
DepMapNodeType.CELL_LINE.value: "data/v0.5/cellModels/cellModels_all.csv",
DepMapNodeType.SEQUENCE_VARIANT.value: "data/v0.5/cellModels/CFE_all.csv"

Thanks.

**Comment by slobentanzer** [comment]
Hi @axh24, this adapter is a prototype we built in an early stage of DepMap with data sent to us by the Iorio lab. We would probably need to update the adapter to include the current dataset, although I don't know if they have kept the structure of the files or not. Would you be interested in looking into this?

**Comment by axh24** [comment]
Hi @slobentanzer,

Thanks you so much for following up with me. Yes, I am interested in trying the early stage of DepMap data if you can share and testing the updated adapter if it's ready.

**Comment by slobentanzer** [comment]
Hi @axh24,
sorry, I guess I was unclear; I don't know if I am allowed to share the pre-release data, and additionally it may not be valuable to look at these early data. My question was whether you would be interested in adapting the pipeline to work with the release/current version of the DepMap dataset. I don't know if the format has changed a lot, but we'd of course be happy to help or make connections to the DepMap team. :)

**Comment by axh24** [comment]
Hi @slobentanzer ,

Thanks for the clarification. Unfortunately, I don't have bandwidth currently to contribute to building DepMap adapter. I look forward to working together in the future.

**Comment by slobentanzer** [comment]
Sure, that is fair. :)

We will certainly come back to this at a point in the near future and update the repo for the full DepMap release.
